import type { Metadata } from "next";
import "./globals.css";

import { Caveat, Inter, Manrope } from "next/font/google";
import Footer from "@/components/Footer";

export const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});
export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
export const caveat = Caveat({
  variable: "--font-caveat",
  display: "swap",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${inter.variable} ${caveat.variable} antialiased`}
      >
        {children}
       
      </body>
    </html>
  );
}
